### ISSUE TITLE
Getting error "open /dev/tpmrm0: device is not a TPM 2.0" on first 2-3 tries to open tpm connection.

### ISSUE THREAD

**Issue by oleksiimoisieiev** [google/go-tpm#186] opened 2020-07-09 14:05 UTC
Hello everyone. 

I'm working on Embedded device with  Infineon SLB9670 TPM2 module. 
Trying to open tpm device by using tpm2.OpenTPM call. 
During the first 2-3 retries, getting the following error:
`open /dev/tpmrm0: device is not a TPM 2.0`

After the 4th retry device opens successfully and I'm able to work with it.
I wrote simple program to reproduce an issue:

```
package main

import (
	"fmt"

	"github.com/google/go-tpm/tpm2"
)

func main() {
	_, err := tpm2.OpenTPM("/dev/tpmrm0")
	if err != nil {
		fmt.Printf("Err %s", err)
		return
	}
	return
}
```

Here is the output:

```
root@v1000:/var# ./1
Err open /dev/tpmrm0: device is not a TPM 2.0
root@v1000:/var# ./1
Err open /dev/tpmrm0: device is not a TPM 2.0
root@v1000:/var# ./1
root@v1000:/var# 
```

As can be seen from the output: 3rd try was successful.

**NOTE** Can't reproduce this issue on the simulator.

**Comment by chrisfenner** [comment] 2020-07-09 14:31
Hi Alexey,

Does the issue reproduce if you go around the kernel resource manager (/dev/tpmrm0) and instead talk to the TPM directly at /dev/tpm0?

**Comment by amoiseev-softheme** [comment] 2020-07-10 05:13
Hi Chris.
I've tried with /dev/tpm0 and issue still reproduced.
Also did some nightly testing and got the following statistic:
Done 632 checks.
In 24 cases - TPM0 error: `Err open /dev/tpm0: device is not a TPM 2.0` 
In 30 cases - TPMRM0 error: `Err open /dev/tpmrm0: device is not a TPM 2.0` 

Looks like some timeout should be added between device open and GetCapabilities.

With tpm2-tss and tpm2-utils - everything works fine.

**Comment by chrisfenner** [comment] 2020-07-10 15:59
Thanks Alexey!

Thanks for doing some statistical testing for this. 😄 Would you be willing to try something else to help us troubleshoot (since I'm assuming we will have some trouble reproducing it without your exact config).

Can you modify [OpenTPM](https://github.com/google/go-tpm/blob/30f8389f7afbbd553e969bf7c59c54e0a83a3373/tpm2/open_other.go#L29) so that we can easily see the actual error returned from `GetManufacturer()`, i.e., replacing line 39:

```
		return nil, fmt.Errorf("open %s: device is not a TPM 2.0", path)
```
with

```
		return nil, err)
```

(This is assuming you don't have a debugger connected, which would be even easier)

Also, can you describe your embedded environment (hardware/OS, etc)?

Thanks
Chris

**Comment by amoiseev-softheme** [comment] 2020-07-11 11:23
Hi Chris. 
Here is output:
```
root@v1000:/var# ./1
Call device tpm0
Err unexpected poll Revents 0x0
root@v1000:/var# ./1
Call device tpm0
Err unexpected poll Revents 0x0
root@v1000:/var# ./1
Call device tpm0
root@v1000:/var# 

```
I'm working with FS-FP5V board (v1000 amd) with Yocto Dunfell release installed.

**Comment by chrisfenner** [comment] 2020-07-13 16:57
Thanks Alexey.

This looks strange to me. Someone who is more expert in Linux syscalls or the way go-tpm polls the TPM may see the issue here, but I don't yet, so I'll ask for some more printf debugging 😅

@rjoleary @josephlr : Does this issue make sense to you folks?

Alexey,
Can you add some logging in [poll_unix.go](https://github.com/google/go-tpm/blob/a2abb88b0a526ef9dce693ca6f1a714876ddcbcc/tpmutil/poll_unix.go#L29):

Of possible interest:

- The value on `f.Fd()` at the beginning of the function
- The first return value from `poll` on line 22


Thanks
Chris

**Comment by amoiseev-softheme** [comment] 2020-07-13 17:42
Hi Chris.

Here is ouput. 
```
root@v1000:/var# ./1 
POLL= 0 FD=3Call device tpm0
Err unexpected poll Revents 0x0root@v1000:/var# ./1 
POLL= 1 FD=3Call device tpm0
root@v1000:/var# 
```
POLL= - is the return value of unix.poll
FD= - f.Fd()

**Comment by twitchy-jsonp** [comment] 2020-07-13 17:54
I would expect a premature return from `poll()` if a signal is received by the process yeah? Perhaps we should put poll in a loop and retry if the poll did not carry an error or an event?

**Comment by chrisfenner** [comment] 2020-07-13 18:01
Thanks Alexey and Tom,

Alexey,

> I've changed timeout from 0 to 100

Is timeout 0 or -1 in your copy of poll_unix.go?

[A few months back](https://github.com/google/go-tpm/commit/a2abb88b0a526ef9dce693ca6f1a714876ddcbcc), this was set to -1 for indefinite timeout. If timeout is actually 0 in your copy of the code, then the behavior may be totally explained.

**Comment by twitchy-jsonp** [comment] 2020-07-13 18:02
> I would expect a premature return from `poll()` if a signal is received by the process yeah? Perhaps we should put poll in a loop and retry if the poll did not carry an error or an event?

I guess we would expect `err == unix.EINTR` in that case then hey

**Comment by amoiseev-softheme** [comment] 2020-07-13 19:24
Hi Chris.
Timeout was 0 in my copy. ~500 checks were done. Everything seems to be fine with timeout 100.
Continue testing

**Comment by chrisfenner** [comment] 2020-07-13 19:37
Thanks Alexey,

Which exact commit/tag of go-tpm are you depending on? I believe that the fixes for this should be in [0.3.0](https://github.com/google/go-tpm/issues/180) when we release that, but depending on head or a recent specific commit may help you in the meantime.

**Comment by amoiseev-softheme** [comment] 2020-07-14 07:02
Hi Chris.
This is entry of my go.mod file:
github.com/google/go-tpm v0.2.1-0.20191106030929-f0607eac7f8a        

Thank you for your help. When do you plan to release 0.3.0?

**Comment by chrisfenner** [comment] 2020-07-14 15:50
Happy to help Alexey!

I don't think we have an estimate other than "soon as we can" for 0.3.0. I think changing to this in your go.mod should unblock you in the meantime:

github.com/google/go-tpm v0.2.1-0.20200624183331-16766ac45214
(Only if you already depend on go-tpm-tools:)
github.com/google/go-tpm-tools@11f284793aa87a8cfb0c1396e77f74654c497d01

Please let me know if that works for you, then I'll close this issue.

Note that since both go-tpm and go-tpm-tools are in 0.x.x, the API is subject to change as we build up the libraries - occasionally this means small conflicts as function signatures change, etc.

**Comment by amoiseev-softheme** [comment] 2020-07-15 12:42
Hi Chris.
Thank you again for your help.
We switched to the commit setting infinite timeout and this helped.
Now my go.mod entry is:
github.com/google/go-tpm v0.2.1-0.20191118184001-a2abb88b0a52  

Will be waiting to 0.3.0 release.

**Comment by josephlr** [comment] 2021-07-01 23:44
Closing as [v0.3.0](https://github.com/google/go-tpm/releases/tag/v0.3.0) was released July 23rd, 2020

Please reopen if you have further issues like this.

**Closed by josephlr** 2021-07-01 23:44 UTC
